#!/usr/bin/env bash
# Creates an RSA key pair named school with passphrase betty
ssh-keygen -q -t rsa -b 4096 -f school -N betty

# Output confirmation
echo "RSA key pair created:"
echo "Private Key: school"
echo "Public Key: school.pub"
